```{r include_packages_2, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(dplyr))
    install.packages("dplyr", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("ggplot2", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("bookdown", repos = "http://cran.rstudio.com")
if(!require(thesisdown)){
  library(devtools)
  devtools::install_github("ismayc/thesisdown")
  }
library(thesisdown)
flights <- read.csv("data/flights.csv")
```

# Tables, Graphics, References, and Labels {#ref-labels}


## Changes in Largest Holdings by Average Weight in Minimum Volatility Index
The top 5 largest holdings in the Minimum Volatility Index by average weight are Verizon, AT&T, Automatic Data Processing, Johnson & Johnson, and McDonald's. 

```{r, echo = FALSE, include=FALSE}
load("~/thesis_final/data/minvol.Rda")

minvol_topweight <- aggregate(weight ~ ticker, data=minvol, FUN=sum)
minvol_topweight <- arrange(minvol_topweight, desc(weight))
minvol_topweight$weight <- minvol_topweight$weight/63
minvol_topweight$rank <- seq.int(nrow(minvol_topweight))
```

```{r fig.cap = paste("Top 5 Holdings in Minimum Volatility Index over Time by Average Weight"), echo=FALSE, include=FALSE}

minvol_topweight <- select(minvol_topweight, rank, ticker, weight)
minvol_topweight <- minvol_topweight[1:5,]

kable(minvol_topweight, 
      col.names = c("Rank", "Ticker", "Average Weight"),
      caption = "Top 5 Holdings in the Minimum Volatility Index over Time by Average Weight",
      longtable = TRUE,
      booktabs = TRUE)
```

```{r, echo = FALSE, include=FALSE}
load("~/thesis_final/data/minvol.Rda")
minvol_sub1 <- filter(minvol, ticker == "VZ" | ticker == "T" | ticker == "ADP" | ticker == "JNJ" | ticker == "MCD")
minvol_sub1 <- select(minvol_sub1, date, ticker, weight)

library(ggplot2)

holdings2<- ggplot() + 
	geom_line(data = filter(minvol_sub1, ticker == "VZ"), aes(x = date, y = weight, color = "VZ")) +
	geom_line(data = filter(minvol_sub1, ticker == "T"), aes(x = date, y = weight, color = "T"))  +
	geom_line(data = filter(minvol_sub1, ticker == "ADP"), aes(x = date, y = weight, color = "ADP"))  +
	geom_line(data = filter(minvol_sub1, ticker == "JNJ"), aes(x = date, y = weight, color = "JNJ"))  +
	geom_line(data = filter(minvol_sub1, ticker == "MCD"), aes(x = date, y = weight, color = "MCD"))  +
	xlab('date') + ylab('weight') + ggtitle('Change in Weights of the Top 5 Holdings in the Minimum Volatility Index over Time')
```

``` {r fig.cap = paste("The 5 largest holdings of the Minimum Volatility Index are VZ, T, ADP, JNJ, and MCD. Since the index's inception, these stocks have generally remained between a weight of 1.3% and 1.7% of the overall portfolio, with the exception of Verizon, which reached around 2% in 2014."), echo=FALSE}
plot(holdings2)
```




