# Conclusions and Future Work
The logistic regression model was statistically resilient and had strong predictive power. Based off of historical data, it was able to correctly predict 86.29% of stocks that were members of the minimum volatility index, and 98.19% of the stocks that were not members. Overall, the logistic regression model had a 96.77% accuracy in distinguishing between stocks that were members of the index, and stocks that were not members of the index. The model is able to calculate a stock’s odds and probability of being a member of the index, if its trailing volatility, trailing beta, price to book ratio, and previous membership information is known. 

## Improved Understanding of Relationships 
This model help add to previous understanding of what traits of a stock are important in its membership in the Minimum Volatility index. The relationship between trailing volatility and current membership in the index was negative; the larger a stock’s volatility, the less likely it is to be in the index. To be specific, for a one unit increase in volatility, the log odds of a stock being an index constituent change by -0.03976. This makes sense, given the Barra Open Optimizer works to create a minimum variance portfolio. The relationship between beta and membership in the minimum volatility index was also negative; the larger the magnitude of a stock’s beta is, the less likely it is to be in the index. To be specific, for a one unit increase in beta, the log odds of a stock being an index constituent change by -4.193. This is also intuitive, given that beta is another measure of a stock’s riskiness. The relationship between price to book ratio and current membership in the minimum volatility index was small in this model; for a one unit increase in price to book ratio, the log odds of a stock being an index constituent increase by 0.00005059. This is an interesting finding, especially in relation to the importance of profitability in defensive equity strategies [@novy2014]. It is important to point out that the coefficient is positive, which means companies with a higher value are more likely to be constituents of the Minimum Volatility index. The relationship between prior index membership and current index membership in the minimum volatility index was by far the most influential. A stock that was a member of the index during the last rebalance has an higher log odds of 5.432 when compared to a stock that was not a member during the last rebalance. 
A stock was over 228 times more likely to a member of the index if it was a member six months. This is logical, considering a vast majority of the stocks in the index remain. There are approximately 180 stocks in the index, and during each rebalance only around 14 are removed [@blackrock2017]. 

This model is also very important in helping determine the specific effect of trailing volatility, trailing beta, price to book ratio, and previous membership on current membership in the Minimum Volatility Index. For example, by using the model it was found that stocks in the index with an average price to book ratio, average volatility, and a beta value in the bottom quartile have a 98% probability of being included in the next period. Similar stocks in the index with an average price to book ratio, average volatility, and a beta value in the top quartile have an 87% probability of remaining. In the data used, the beta value in the bottom quartile was 0.8262 and the beta value in the top quartile was 1.2651. Thus, a reduction in beta by 0.4389 results in a current member of the index having an 11% higher probability of remaining in the index. Stocks that are not current members of the index that have an average price to book ratio, average volatility, and a beta value in the bottom quartile have a 16% probability of being added to the index during the next rebalance. Stocks that are not current members of the index that have an average price to book ratio, average volatility, and a beta value in the top quartile have a 3% probability of being added. Thus, in this case, a reduction in beta by 0.4389 results in a current member of the index having an 13% higher probability of remaining in the index. 

## Sector-Specific Risk
Some sectors were overweight or underweight in the Minimum Volatility Index when compared to its parent index, which could have implications about sector-specific risk. Macro-effects, like industry specific effects mentioned in previous literature, have been shown to be significant  in effecting a portfolio’s risk-adjusted returns [@baker2014]. Based off of the findings in this thesis, energy, consumer discretionary, industrials, and materials stocks were shown to be underweight in the Minimum Volatility Index since 2011 when compared to the parent index. This indicates that stocks in these sectors could be inherently more volatile than stocks in other sectors. Moreover, the consumer staples, healthcare, and utilities industries were consistently overweight in the Minimum Volatility Index since 2011 when compared to the parent index. This could imply that companies in these sectors are inherently less volatile than companies in other sectors.

## Future Models
The logistic regression model took into account all of the data from the months when a rebalance occurred. However, predictive power could increase through the use of more specific models. Sector-specific models could have been created. As shown in the analysis, some sectors are more volatile and risky than others, so using a model that is specific to stocks in a particular industry could increase the accuracy of predicting which stocks will be in the Minimum Volatility Index after the next rebalance. Moreover, sector could have been used as a categorical predictor variable in the current regression model. 

Observing the significance of previous index membership as a predictor variable in the regression model, it could make sense to create two separate models: one for stocks currently in the Minimum Volatility index, and one for stocks that are not. This could also help for tailored investment applications, as there would be one model used for short-selling stocks that are predicted to leave the index, and a model used for purchasing stocks that are predicted to enter the index. Creating models by month could be telling too; by combining the May and November data, the current model does not take into account specific factors that might be unique to rebalancing that occurs in either period. Thus, a separate model for May and a separate model for November could also have additional predictive power. 

## Investment Implications  
Given the accuracy and predictive abilities of the logistic regression model, there are several applications to the world of finance. If the model can accurately forecast index membership in advance of its rebalancing, investors could long stocks that are predicted to be added to the index, and short the stocks that are expected to be removed from the index. Given that approximately 20 stocks are added and 14 stocks are removed from the index during each rebalance [@blackrock2017], one strategy could be to purchase stock in the top companies that are currently not in the index but have the high probabilities of being added, and short-selling stocks that are currently in the minimum volatility but have the lowest probability of remaining. When the iShares MSCI Minimum Volatility ETF is rebalanced, stocks that were added enjoyed an average increase in price the day after the announcement of 0.63%, and stocks that were removed lost an average of 0.57% of price after the announcement [@huij2016]. Though the values are small by themselves, on an annualized basis, an accurate model could lead to a very lucrative investment strategy. A computer algorithm could be developed to systematically trade this strategy. 
